@startuml

abstract class Subject{

 + abstract void : visit()
}

class RealSubject{

  + void : visit()
}

class ProxySubject{

   - RealSubject mSubject

   + void : visit()
}


Subject <|-- RealSubject
Subject <|-- ProxySubject

ProxySubject --> RealSubject

@enduml